sudo: required
services: 
  - docker

before_install:
  - docker build udaygandagari/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true udaygandagari/react-test npm test

after_success:
  - docker build -t udaygandagari/multicontainer-client ./client
  - docker build -t udaygandagari/multicontainer-nginx ./nginx
  - docker build -t udaygandagari/multicontainer-server ./server
  - docker build -t udaygandagari/multicontainer-worker ./worker

#Login to docker CLI with credentials
- echo "DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin 

#Take the images and push to dockerhub
- docker push udaygandagari/multicontainer-client
- docker push udaygandagari/multicontainer-nginx
- docker push udaygandagari/multicontainer-server
- docker push udaygandagari/multicontainer-worker